openapi: 3.0.1
info:
  title: API de pacientes
  description: >
    Esta API se encarga de gestionar pacientes y tratamientos en una clínica veterinaria.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
  - url: http://localhost:5173/
    description: Frontend de Veterinarios

tags:
  - name: pacientes
    description: Maneja la información de los pacientes y sus tratamientos

paths:
  /pacientes/login:
    post:
      summary: Iniciar sesión de paciente
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PacienteLogin'
      responses:
        '200':
          description: Inicio de sesión exitoso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PacientePerfilResponse'

  /pacientes/registro:
    post:
      summary: Registro de nuevo paciente
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PacienteRegistro'
      responses:
        '200':
          description: Paciente registrado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Mensaje de éxito

  /pacientes/{id}:
    get:
      summary: Obtener detalles de un paciente
      parameters:
        - name: id
          in: path
          required: true
          description: ID del paciente
          schema:
            type: string
      responses:
        '200':
          description: Detalles del paciente obtenidos correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PacientePerfilResponse'

    put:
      summary: Actualizar información de un paciente
      parameters:
        - name: id
          in: path
          required: true
          description: ID del paciente a actualizar
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PacienteActualizacion'
      responses:
        '200':
          description: Información del paciente actualizada correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Mensaje de éxito

  /pacientes/recuperar-contrasena:
    post:
      summary: Enviar solicitud de recuperación de contraseña
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecuperarContrasena'
      responses:
        '200':
          description: Solicitud de recuperación de contraseña enviada correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Mensaje de éxito

  /pacientes/listar:
    get:
      summary: Listar todos los pacientes
      responses:
        '200':
          description: Listado de pacientes obtenido correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PacientePerfilResponse'

  /pacientes/crear:
    post:
      summary: Crear un nuevo paciente
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PacienteCreacion'
      responses:
        '200':
          description: Paciente creado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Mensaje de éxito

components:
  schemas:
    PacienteLogin:
      type: object
      properties:
        email:
          type: string
          description: Correo electrónico del paciente
        password:
          type: string
          description: Contraseña del paciente
      required:
        - email
        - password

    PacienteRegistro:
      type: object
      properties:
        nombre:
          type: string
          description: Nombre del paciente
        propietario:
          type: string
          description: Propietario del paciente
        direccion:
          type: string
          description: Dirección del paciente
        telefono:
          type: number
          description: Teléfono del paciente
        email:
          type: string
          description: Correo electrónico del paciente
        password:
          type: string
          description: Contraseña del paciente
      required:
        - nombre
        - propietario
        - direccion
        - telefono
        - email
        - password

    PacientePerfilResponse:
      type: object
      properties:
        nombre:
          type: string
          description: Nombre del paciente
        propietario:
          type: string
          description: Propietario del paciente
        direccion:
          type: string
          description: Dirección del paciente
        telefono:
          type: number
          description: Teléfono del paciente
        email:
          type: string
          description: Correo electrónico del paciente
        _id:
          type: string
          description: ID del paciente
      required:
        - nombre
        - propietario
        - direccion
        - telefono
        - email
        - _id

    PacienteActualizacion:
      type: object
      properties:
        nombre:
          type: string
          description: Nuevo nombre del paciente
        propietario:
          type: string
          description: Nuevo propietario del paciente
        direccion:
          type: string
          description: Nueva dirección del paciente
        telefono:
          type: number
          description: Nuevo teléfono del paciente
        email:
          type: string
          description: Nuevo correo electrónico del paciente
        password:
          type: string
          description: Nueva contraseña del paciente
      required:
        - nombre
        - propietario
        - direccion
        - telefono
        - email
        - password

    PacienteCreacion:
      type: object
      properties:
        nombre:
          type: string
          description: Nombre del paciente
        propietario:
          type: string
          description: Propietario del paciente
        direccion:
          type: string
          description: Dirección del paciente
        telefono:
          type: number
          description: Teléfono del paciente
        email:
          type: string
          description: Correo electrónico del paciente
        password:
          type: string
          description: Contraseña del paciente
      required:
        - nombre
        - propietario
        - direccion
        - telefono
        - email
        - password

    RecuperarContrasena:
      type: object
      properties:
        email:
          type: string
          description: Correo electrónico del paciente
      required:
        - email
