openapi: 3.0.1
info:
  title: API de Veterinaria
  description: >
    Esta API se encarga de crear un veterinario que pueda generar pacientes y los tratamientos de este paciente.
  version: 1.0.0
servers:
  - url: https://localhost:3000/api
tags:
  - name: veterinarios
    description: Maneja la información de los veterinarios que luego pueden registrar la información de pacientes y tratamientos

paths:
  /veterinarios/login:
    post:
      summary: Iniciar sesión de veterinario
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VeterinarioLogin'
      responses:
        '200':
          description: Inicio de sesión exitoso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VeterinarioPerfil'

  /veterinarios/registro:
    post:
      summary: Registro de nuevo veterinario
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VeterinarioRegistro'
      responses:
        '200':
          description: Veterinario registrado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Mensaje de éxito

  /veterinarios/confirmar/{token}:
    get:
      summary: Confirmar cuenta de veterinario
      parameters:
        - name: token
          in: path
          description: Token de confirmación
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Cuenta confirmada correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Mensaje de éxito

  /veterinarios/listar:
    get:
      summary: Listar veterinarios
      responses:
        '200':
          description: Lista de veterinarios registrados
          content:
            application/json:
              schema:
                type: object
                properties:
                  res:
                    type: string
                    description: Respuesta

  /veterinarios/perfil:
    get:
      summary: Obtener perfil del veterinario
      responses:
        '200':
          description: Perfil del veterinario obtenido correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VeterinarioPerfil'

  /veterinarios/actualizar-password:
    put:
      summary: Actualizar password del veterinario
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VeterinarioActualizarPassword'
      responses:
        '200':
          description: Password actualizado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Mensaje de éxito

  /veterinarios/detalle/{id}:
    get:
      summary: Obtener detalle de un veterinario
      parameters:
        - name: token
          in: header
          description: Token de autenticación
          required: true
          schema:
            type: string
        - name: id
          in: path
          description: Identificador del veterinario a obtener
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detalle del veterinario obtenido correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VeterinarioPerfil'

  /veterinarios/actualizar-perfil/{id}:
    put:
      summary: Actualizar perfil del veterinario
      parameters:
        - name: token
          in: header
          description: Token de autenticación
          required: true
          schema:
            type: string
        - name: id
          in: path
          description: Identificador del veterinario a actualizar
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VeterinarioActualizarPerfil'
      responses:
        '200':
          description: Perfil del veterinario actualizado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Mensaje de éxito

components:
  schemas:
    VeterinarioLogin:
      type: object
      properties:
        email:
          type: string
          description: Correo electrónico del veterinario
        password:
          type: string
          description: Contraseña del veterinario
      required:
        - email
        - password

    VeterinarioRegistro:
      type: object
      properties:
        nombre:
          type: string
          description: Nombre del veterinario
        apellido:
          type: string
          description: Apellido del veterinario
        direccion:
          type: string
          description: Dirección del veterinario
        telefono:
          type: number
          description: Teléfono del veterinario
        email:
          type: string
          description: Correo electrónico del veterinario
        password:
          type: string
          description: Contraseña del veterinario
      required:
        - nombre
        - apellido
        - email
        - password

    VeterinarioPerfil:
      type: object
      properties:
        nombre:
          type: string
          description: Nombre del veterinario
        apellido:
          type: string
          description: Apellido del veterinario
        direccion:
          type: string
          description: Dirección del veterinario
        telefono:
          type: number
          description: Teléfono del veterinario
        email:
          type: string
          description: Correo electrónico del veterinario
        _id:
          type: string
          description: ID del veterinario

    VeterinarioActualizarPerfil:
      type: object
      properties:
        nombre:
          type: string
          description: Nuevo nombre del veterinario
        apellido:
          type: string
          description: Nuevo apellido del veterinario
        direccion:
          type: string
          description: Nueva dirección del veterinario
        telefono:
          type: number
          description: Nuevo teléfono del veterinario
        email:
          type: string
          description: Nuevo correo electrónico del veterinario

    VeterinarioActualizarPassword:
      type: object
      properties:
        passwordactual:
          type: string
          description: Contraseña actual del veterinario
        passwordnuevo:
          type: string
          description: Nueva contraseña del veterinario


